"""Password hashing and token generation (Phase 03).

Two very different kinds of secret live here and must not share a strategy:

- **passwords** — low entropy, attacker-controlled, so they get a slow, memory-hard
  Argon2id hash.
- **session / CSRF tokens** — generated by us from a CSPRNG (high entropy), so a
  single SHA-256 is enough: there is nothing to brute force.
"""

import hashlib
import secrets

from argon2 import PasswordHasher
from argon2.exceptions import InvalidHashError, VerificationError

SESSION_TOKEN_BYTES = 32
CSRF_TOKEN_BYTES = 32

SESSION_COOKIE = "officehub_session"
CSRF_COOKIE = "csrf_token"
CSRF_HEADER = "X-CSRF-Token"

_hasher = PasswordHasher()

# Verified against when the email is unknown, so a missing account costs the same
# time as a wrong password (FR-AUTH-002).
_DUMMY_HASH = _hasher.hash("officehub-timing-equalizer")


def hash_password(password: str) -> str:
    return _hasher.hash(password)


def verify_password(password: str, password_hash: str | None) -> bool:
    if password_hash is None:
        _hasher.verify(_DUMMY_HASH, password)
        return False
    try:
        return _hasher.verify(password_hash, password)
    except (VerificationError, InvalidHashError):
        return False


def needs_rehash(password_hash: str) -> bool:
    return _hasher.check_needs_rehash(password_hash)


def new_session_token() -> str:
    return secrets.token_urlsafe(SESSION_TOKEN_BYTES)


def new_csrf_token() -> str:
    return secrets.token_urlsafe(CSRF_TOKEN_BYTES)


def hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()